In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv('insurance_pre.csv')

In [5]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [6]:
dataset = pd.get_dummies(dataset, drop_first=True)

In [7]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [8]:
independent = dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]

In [9]:
dependent = dataset[['charges']]

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent,test_size=0.3, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid = {
    'kernel':['rbf', 'poly', 'sigmoid', 'linear'],
    'C':[10,100,1000,2000,3000],
    'gamma':['auto','scale']
}

grid = GridSearchCV(SVR(), param_grid, refit=True, verbose=3, n_jobs=-1 )
grid.fit(x_train, y_train)

Fitting 5 folds for each of 40 candidates, totalling 200 fits

c:\Hope\.venv\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(estimator=SVR(), n_jobs=-1,
             param_grid={'C': [10, 100, 1000, 2000, 3000],
                         'gamma': ['auto', 'scale'],
                         'kernel': ['rbf', 'poly', 'sigmoid', 'linear']},
             verbose=3)

In [16]:
print(grid.best_estimator_)

SVR(C=3000, kernel='poly')

In [17]:
grid_predict = grid.predict(x_test)

In [18]:
grid_predict

array([ 9882.23553045,  8684.53726052, 47863.91492801, 12571.3296839 ,
       10503.41343965,  4754.93723666,  1443.94974332, 11161.657231  ,
        7435.84538836,  5371.62749203,  6792.36540753, 10061.14110577,
        7632.07502973,  4871.76871538, 25340.31666642, 10702.78951231,
       12523.59208886,  3559.80058082,  6538.68332237, 24014.94367286,
       25935.15514707, 12148.61708249,  9691.29174851, 30533.71413143,
        1963.47262983,  4967.98361807,  4445.33159778,  8003.49970394,
        4385.68529386,  8313.99557978,  7894.30531574, 51334.29195098,
       13004.91484206, 10251.92921715, 12711.42308372,  4153.88138193,
        8739.42694068, 35968.17012456, 35436.61473361,  2077.05999458,
        5945.32507383,  3376.59733562, 27298.90556466, 44665.58571445,
       32712.02939249,  3248.44366366, 10704.52721091,  7044.43520973,
        4729.54504139, 12142.93055349,  2793.08923534,  2960.73592137,
       30936.72609045, 42934.61243676, 11849.41436963,  3311.33971211,
        2881.70649678,  8672.39298937,  9944.89603544, 13098.45882487,
        1124.12958903, 36096.43185816, 13950.72721413,  9784.09263893,
       10282.43920497, 10072.85587107, 22653.818399  , 34039.44130597,
        3000.57564297,  8017.64348207, 13099.0202627 , 11674.61116259,
       19117.80648875, 13936.90381547, 12961.2094236 , 12701.41915414,
        7772.40831592,  8051.20763665, 24419.65627755, 44831.97870629,
       11088.74361983, 55127.90610426,  1917.60740494,  7822.03899316,
       40129.17164918, 22593.98569503,  4033.1068808 ,  2776.23778673,
       12481.58583512, 36639.31940305,  6249.94602188, 10245.09931267,
        3205.92186049,  8589.96978039,  4582.49782023,  5176.03683328,
       37119.46845005, 32892.943304  ,  5437.10031731, 10592.33643247,
        2155.39240645,  5744.72093302,  4804.25994812, 38177.21935775,
       29738.86148437,  3695.40095061, 11158.27848813,  3867.63757389,
       11348.35283724, 40816.91696321, 12440.82716329,  4782.97834571,
        8964.74523646, 23957.49738187, 52370.03944239,  7509.86971552,
        2034.32293919,  8663.70898858, 12477.27400497,  9100.77149955,
       40533.28028403, 10785.05462643, 14407.88172532,  5283.32122263,
        7868.55791854,  4965.44469655, 26841.94423531, 22073.86673503,
       51216.72283054,  1792.24909441,  8350.3190839 ,  1806.83971104,
        6458.24462102,  9318.09335121, 33687.16049455, 32135.77726341,
       25378.69977922, 10177.79834336, 21884.35044824,  2729.0136614 ,
        2038.01439595, 10307.76255141,  9582.01591354,  9878.58257072,
        5156.39642821, 14386.07882626, 12814.78459798,  3445.68085217,
        1178.04641992, 10669.88627792,  6399.62761538, 43416.97061333,
        9584.21745794,  1653.26779917,  2540.67639022,  6899.26812663,
        2638.81023173,  1626.61376887, 10702.94239427,  9888.57864153,
        4521.7558114 , 12989.87638033, 12801.72472401,  9684.61913981,
        4924.24773795,  4166.09474561, 11723.56066478,  5829.66518375,
        4483.37811619,  1647.4574648 ,  4237.27512395,  4253.09635011,
        8113.73509247,  2453.47501649,  4450.42711012,  4407.04224632,
        4284.42204287,  6502.30066287, 34420.99161606,   839.15494639,
       10720.2176525 ,  6744.16224229, 10962.74308212,  3058.93766216,
        5676.24731769, 31235.78089246,  1906.70468972,  2639.92909553,
       14367.51010564,  9836.49457321, 38197.58977171,  4242.99224767,
        5946.53072287, 26292.00886939,  2668.47740425,  2262.88206194,
        6318.83035786,  6459.36987877,  4780.12766836,  4508.27746513,
       10885.22583793, 42691.4590069 , 11762.30201311, 22439.44550769,
        4615.06828211, 42589.38695713,  3559.20576494,  9220.77799485,
        6415.51352806,   891.14373095,  8685.83796343, 13462.92679384,
        5047.99465383,  2757.3173375 ,  6784.58508966,  2312.91431835,
        6457.86068333,  5394.07107408, 13998.7060166 ,  7249.4946164 ,
        6708.93811158,  7705.84464283,  8480.39148416,  3125.42869797,
       11816.39321741, 13909.56525446, 12242.93121631, 12029.71228455,
        7182.51136452,  2490.50428427,   919.73168046,  8246.12814113,
       12228.53035534,  3379.12338372,  5098.39133218,  7327.51674393,
        8970.11219891, 27288.13410862,  6061.87794121, 11162.84029699,
        5925.03582558, 28864.4019452 ,  7823.73891741,  7220.96723358,
        8231.74673008, 10216.83672307,  2638.33242094,  7762.97104514,
        2447.54602071,  6869.28812178, 26555.32890576, 35766.72750977,
        4422.35336316,  3827.71125846,  1488.67060189,   873.57488309,
        7892.38805697,  1672.54146403,  4315.67195009,  4005.03601895,
        9206.20644602, 29342.79742475, 39714.04169247, 14512.11097852,
        6781.86556103, 10960.5117737 , 40453.59991056,  9137.86944255,
       36787.32259024,  1045.2565007 , 34112.31120262,  5377.62992546,
       12335.47310115,  3920.50284634, 38162.02906541,  5663.63323349,
        9538.23863824, 10660.11827027,  2224.72751154, 13127.99373715,
       11906.31561515,  4602.13390297, 12193.24779875,  1513.27608408,
        6269.52402159,  3615.86952553,  9778.06613062, 25076.82384897,
        3218.3107938 ,   837.14927988,  2207.75364435, 42761.33601871,
        9006.34861442,  5006.50355836, 11781.87363407, 11232.2700678 ,
       28562.9778025 ,  6870.07632497,  5425.98137919,  8615.59613949,
        1174.88508554,  2588.90201907,  7809.15815171, 20669.02302626,
       13485.18222778,  2487.58221053,  3720.19003498,  8775.68991854,
        9214.1770439 , 11023.21601256, 26912.35997168,  6484.4987279 ,
       13441.70088003,  1763.04471289,  5912.66145995,  4573.33934446,
        8362.93614229,  1908.42345675,  6677.94406254, 46550.3461637 ,
        3554.20300832,  4153.10111427,  1755.31261803,  8505.36760776,
        4094.69854855, 12277.4140058 , 38731.45208681, 17448.77028259,
        8961.45512226, 43479.85275289, 12531.48409751,  4629.19611443,
        9561.32149564,  3708.79822886, 32675.69313092,  5112.65841301,
       13652.00221054,  1751.88183348, 16492.71150228,  3414.95085504,
       26980.7513681 ,  6249.33522912,  2303.96335261, 41793.97259644,
        5619.35010309,  5487.47879652, 32781.70858763,  1169.30686382,
        8224.73734524,  2196.27846101, 12838.65206101,  3979.72169115,
        5795.47046378,  5161.93480756, 42083.09586955,  8787.20254665,
       30646.26528434, 33705.17634038,  6063.75451907,  9174.86681756,
        1106.1396774 ,  3549.66062399,  2684.90084026,  8774.76841733,
       40398.51440606, 11350.78349778,  1694.13231126, 12060.96176167,
        2361.47687331,  7682.3143668 ,  4085.52579565,  2144.63722311,
        3441.85555571, 31650.49209198,  7316.96654362,  1603.6094843 ,
       41047.18689536, 10919.16668935, 39823.79032301, 11798.34118947,
        4880.58978817,  2432.5049211 ,  1960.01922554, 10087.51701366,
        5370.74312817,  1565.50270477, 10198.23596546,  7391.78869883,
        6391.18278686,  4220.98406724,  2630.01682721, 38031.53752854,
        1664.19121047,  9182.8047174 ,  1673.55753297,  7610.29290329,
       10601.45909977,  4119.64101549, 17493.37707706, 10252.55211956,
       14638.82310858, 13744.49114367])

In [19]:
from sklearn.metrics import r2_score
r_score = r2_score(y_test, grid_predict)

In [21]:
r_score

0.859893008449439

In [24]:
table = pd.DataFrame.from_dict(grid.cv_results_)

In [25]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_gamma,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.213172,0.039135,0.063973,0.019027,10,auto,rbf,"{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}",0.004055,0.013366,-0.103821,-0.095119,-0.101604,-0.056625,0.053504,35
1,0.127346,0.015502,0.014853,0.002816,10,auto,poly,"{'C': 10, 'gamma': 'auto', 'kernel': 'poly'}",0.056274,0.069532,-0.045601,-0.025079,-0.049592,0.001107,0.051309,32
2,0.109689,0.017290,0.016145,0.001682,10,auto,sigmoid,"{'C': 10, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.049905,0.075905,-0.046585,-0.041004,-0.046507,-0.001657,0.053391,34
3,0.059090,0.001537,0.009860,0.000755,10,auto,linear,"{'C': 10, 'gamma': 'auto', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
4,0.080097,0.004824,0.052628,0.006824,10,scale,rbf,"{'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}",0.004126,0.013244,-0.103775,-0.095165,-0.101602,-0.056634,0.053486,36
5,0.061243,0.003479,0.011625,0.002346,10,scale,poly,"{'C': 10, 'gamma': 'scale', 'kernel': 'poly'}",0.054964,0.071297,-0.046513,-0.024157,-0.049652,0.001188,0.051594,31
6,0.088931,0.003330,0.017240,0.002217,10,scale,sigmoid,"{'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.049644,0.076323,-0.046798,-0.040824,-0.046521,-0.001635,0.053474,33
7,0.064330,0.004989,0.011602,0.001809,10,scale,linear,"{'C': 10, 'gamma': 'scale', 'kernel': 'linear'}",0.377969,0.479601,0.317872,0.337979,0.324422,0.367569,0.059777,25
8,0.085254,0.005883,0.066178,0.014468,100,auto,rbf,"{'C': 100, 'gamma': 'auto', 'kernel': 'rbf'}",0.300573,0.339474,0.173708,0.217991,0.183375,0.243024,0.065733,29
9,0.074123,0.015792,0.012008,0.001512,100,auto,poly,"{'C': 100, 'gamma': 'auto', 'kernel': 'poly'}",0.540643,0.575051,0.474839,0.535730,0.424640,0.510181,0.053582,21
10,0.101380,0.007003,0.016699,0.001145,100,auto,sigmoid,"{'C': 100, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.478364,0.561673,0.428331,0.450454,0.431701,0.470105,0.049110,24
11,0.093455,0.011666,0.012605,0.001858,100,auto,linear,"{'C': 100, 'gamma': 'auto', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
12,0.082191,0.002207,0.057418,0.004562,100,scale,rbf,"{'C': 100, 'gamma': 'scale', 'kernel': 'rbf'}",0.301041,0.338741,0.174086,0.217641,0.183403,0.242982,0.065542,30
13,0.079634,0.007764,0.013299,0.002846,100,scale,poly,"{'C': 100, 'gamma': 'scale', 'kernel': 'poly'}",0.537117,0.579373,0.471840,0.537966,0.424478,0.510155,0.054955,22
14,0.099459,0.005826,0.019757,0.002945,100,scale,sigmoid,"{'C': 100, 'gamma': 'scale', 'kernel': 'sigmoid'}",0.478930,0.563200,0.427152,0.451250,0.432199,0.470546,0.049762,23
15,0.110656,0.009327,0.013773,0.001912,100,scale,linear,"{'C': 100, 'gamma': 'scale', 'kernel': 'linear'}",0.584474,0.655818,0.553380,0.576939,0.546881,0.583498,0.038787,19
16,0.130700,0.015984,0.065235,0.009184,1000,auto,rbf,"{'C': 1000, 'gamma': 'auto', 'kernel': 'rbf'}",0.733044,0.746232,0.686773,0.717920,0.649158,0.706625,0.034902,12
17,0.133984,0.018657,0.014406,0.004269,1000,auto,poly,"{'C': 1000, 'gamma': 'auto', 'kernel': 'poly'}",0.829631,0.802622,0.799620,0.800321,0.735580,0.793555,0.031072,7
18,0.121038,0.020796,0.019851,0.004478,1000,auto,sigmoid,"{'C': 1000, 'gamma': 'auto', 'kernel': 'sigmoid'}",0.296082,0.372281,0.216401,0.291265,0.351325,0.305471,0.054387,28
19,0.119221,0.016793,0.014786,0.004634,1000,auto,linear,"{'C': 1000, 'gamma': 'auto', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
20,0.128090,0.012556,0.057778,0.007555,1000,scale,rbf,"{'C': 1000, 'gamma': 'scale', 'kernel': 'rbf'}",0.733334,0.745892,0.687037,0.717769,0.649174,0.706641,0.034825,11
21,0.125297,0.031251,0.011082,0.000926,1000,scale,poly,"{'C': 1000, 'gamma': 'scale', 'kernel': 'poly'}",0.828213,0.802622,0.799348,0.800587,0.735555,0.793265,0.030757,8
22,0.106747,0.014054,0.024469,0.007768,1000,scale,sigmoid,"{'C': 1000, 'gamma': 'scale', 'kernel': 'sigmo...",0.400044,0.366097,0.242217,0.288461,0.351407,0.329645,0.056742,27
23,0.113026,0.013257,0.012881,0.002722,1000,scale,linear,"{'C': 1000, 'gamma': 'scale', 'kernel': 'linear'}",0.605304,0.588725,0.623230,0.537931,0.616726,0.594383,0.030560,17
24,0.124660,0.002179,0.053637,0.002791,2000,auto,rbf,"{'C': 2000, 'gamma': 'auto', 'kernel': 'rbf'}",0.814076,0.781092,0.794081,0.794075,0.733656,0.783396,0.027014,10
25,0.222932,0.054893,0.011627,0.001766,2000,auto,poly,"{'C': 2000, 'gamma': 'auto', 'kernel': 'poly'}",0.845403,0.805639,0.816733,0.805143,0.754961,0.805576,0.029233,4
26,0.105431,0.004850,0.016631,0.002025,2000,auto,sigmoid,"{'C': 2000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-0.401855,-0.508082,-0.452827,-0.751013,-0.111859,-0.445127,0.205197,38
27,0.137850,0.019596,0.010456,0.000643,2000,auto,linear,"{'C': 2000, 'gamma': 'auto', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
28,0.126919,0.011684,0.052534,0.004045,2000,scale,rbf,"{'C': 2000, 'gamma': 'scale', 'kernel': 'rbf'}",0.814295,0.780971,0.794227,0.793983,0.733663,0.783428,0.027068,9
29,0.186379,0.023334,0.010977,0.000533,2000,scale,poly,"{'C': 2000, 'gamma': 'scale', 'kernel': 'poly'}",0.845581,0.805624,0.816612,0.805133,0.754962,0.805582,0.029272,3
30,0.107953,0.006212,0.017903,0.002944,2000,scale,sigmoid,"{'C': 2000, 'gamma': 'scale', 'kernel': 'sigmo...",-0.385658,-0.537098,-0.474912,-0.477335,-0.111187,-0.397238,0.150976,37
31,0.133777,0.015649,0.009968,0.000505,2000,scale,linear,"{'C': 2000, 'gamma': 'scale', 'kernel': 'linear'}",0.605277,0.583646,0.697368,0.532547,0.681425,0.620053,0.061555,15
32,0.138757,0.013585,0.052774,0.002798,3000,auto,rbf,"{'C': 3000, 'gamma': 'auto', 'kernel': 'rbf'}",0.828670,0.790265,0.811049,0.812892,0.741829,0.796941,0.030140,6
33,0.331256,0.174712,0.010573,0.001209,3000,auto,poly,"{'C': 3000, 'gamma': 'auto', 'kernel': 'poly'}",0.846775,0.805323,0.817309,0.805191,0.758994,0.806718,0.028279,2
34,0.105494,0.008892,0.015339,0.000919,3000,auto,sigmoid,"{'C': 3000, 'gamma': 'auto', 'kernel': 'sigmoid'}",-1.090896,-1.761043,-1.734344,-2.304377,-1.050280,-1.588188,0.469215,39
35,0.152834,0.005626,0.010472,0.001194,3000,auto,linear,"{'C': 3000, 'gamma': 'auto', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13
36,0.128872,0.004288,0.053352,0.004341,3000,scale,rbf,"{'C': 3000, 'gamma': 'scale', 'kernel': 'rbf'}",0.828795,0.790105,0.811123,0.812857,0.741835,0.796943,0.030174,5
37,0.375377,0.141665,0.011371,0.005979,3000,scale,poly,"{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}",0.846874,0.805331,0.817283,0.805239,0.758988,0.806743,0.028307,1
38,0.104644,0.005025,0.016153,0.001547,3000,scale,sigmoid,"{'C': 3000, 'gamma': 'scale', 'kernel': 'sigmo...",-1.761871,-2.139307,-1.704369,-2.340839,-1.048739,-1.799025,0.443311,40
39,0.144272,0.014423,0.008474,0.002005,3000,scale,linear,"{'C': 3000, 'gamma': 'scale', 'kernel': 'linear'}",0.657470,0.583501,0.697875,0.529117,0.655785,0.624750,0.060379,13

In [26]:
age_input = float(input("Age:"))
bmi_input = float(input("BMI:"))
children_input = float(input("Children:"))
sex_male_input = int(input("Sex Male 0 or 1:"))
smoker_yes_input = int(input("Smoker Yes 0 or 1:"))

In [27]:
grid.predict([[age_input, bmi_input, children_input, sex_male_input, smoker_yes_input]])

array([2370377.90471038])